runtime: python39
entrypoint: gunicorn -b :$PORT main:app
instance_class: F2
runtime_config:
  python_version: 3.7
env_variables:
  CLOUD_STORAGE_BUCKET: <deployment-flask>
automatic_scaling:
  target_cpu_utilization: 0.65
